@WebApi_HostAddress = http://localhost:5081

### 1. Pobierz wszystkich (Paginacja)
GET {{WebApi_HostAddress}}/api/contacts?page=1&size=10
Accept: application/json

###

### 2. Dodaj nową osobę (POST)
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName": "Nowak",
  "email": "adam@wsei.edu.pl",
  "phone": "48123456789"
}

###

### 3. Pobierz konkretną osobę ()
GET {{WebApi_HostAddress}}/api/contacts/a323d8f2-e978-4b5b-afda-5cc748c5bf12
Accept: application/json

###

### 4. Edytuj istniejącą osobę (PUT)
PUT {{WebApi_HostAddress}}/api/contacts/a323d8f2-e978-4b5b-afda-5cc748c5bf12
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName": "Nowakowski",
  "email": "adam.nowakowski@wsei.edu.pl",
  "phone": "48 999 888 777"
}

###

### 5. Test walidacji ()
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName": "Nowak"
}

### 6. Dodanie notatki do osoby
POST {{WebApi_HostAddress}}/api/contacts/66fbbd4f-bb8f-47bd-8e99-9cd6308aac56/notes
Content-Type: application/json

{
  "content": "New note"
}

###

### 7. Pobranie notatek osoby
GET {{WebApi_HostAddress}}/api/contacts/66fbbd4f-bb8f-47bd-8e99-9cd6308aac56/notes
Content-Type: application/json

###

### 8. Usunięcie notatki osoby
DELETE {{WebApi_HostAddress}}/api/contacts/66fbbd4f-bb8f-47bd-8e99-9cd6308aac56/notes/e81fad59-bce8-4c01-90f9-62f489e7823b
Content-Type: application/json

###